language: python
sudo: required
python:
  - "3.6"
env: TEST_SUITE=test-main
matrix:
  include:
  - python: "3.6"
    env: TEST_SUITE=test-static-analysis
    addons:
      postgresql: "9.3"
install:
  - pip install virtualenv
  - python -m venv env
  - source env/bin/activate
  - pip install -U -r  req.txt
script:
  - python bot.py
after_success:
  - pip install codecov
  - codecov