language: python
sudo: required
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env: TEST_SUITE=test-main
matrix:
  include:
  - python: "3.6"
    env: TEST_SUITE=test-static-analysis
    addons:
      postgresql: "9.3"
install:
  - sudo rm -vf /etc/apt/sources.list.d/*
  - sudo apt-get update
  - pip install virtualenv
  - python3 venv env
  - source env/bin/activate
  - pip install -r req.txt
script:
  - python bot.py
after_success:
  - pip install codecov
  - codecov